name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: 
        docker login --username bananamcgee --password ${{ secrets.GH_PAT }} ghcr.io
        docker build . -t ghcr.io/bananamcgee/helloword-ghcr:latest
        docker push ghcr.io/bananamcgee/helloword-ghcr:latest
